#!/usr/bin/env python3
"""Build a CCS project: SysConfig CLI -> gmake (auto-generates makefile if needed).

Chip-adaptive: all chip-specific values (startup file, macro, linker cmd, LP board)
are derived from config.json's `chip` field, so a single build.py works for any
MSPM0 board (G3507, G3519, L1306, ...).
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path


def _load_config(config_path: str) -> dict:
    try:
        with open(config_path, encoding="utf-8") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


# Suffixes of SysConfig-generated peripheral macros the .c usually references.
# Used to print ground-truth macro names so the agent never guesses them.
_MACRO_SUFFIXES = (
    "_PORT", "_PIN", "_IOMUX", "_INST", "_IIDX", "_IDX",
    "_IRQN", "_INT_IRQN", "_INST_IRQHandler",
)
_MACRO_RE = re.compile(
    r'^#define\s+([A-Z_][A-Z0-9_]*(?:'
    + "|".join(s for s in _MACRO_SUFFIXES)
    + r'))\b[ \t]+(.+?)[ \t]*$',
    re.MULTILINE,
)


def print_generated_macros(proj: Path) -> bool:
    """Grep ti_msp_dl_config.h and print every peripheral macro (PORT/PIN/INST/...).

    Lets the agent write the .c with ground-truth macro names instead of guessing,
    eliminating the first-build failure caused by wrong macro names.
    Returns True if the header existed and was parsed.
    """
    header = proj / "ti_msp_dl_config.h"
    if not header.exists():
        print(f"[macros] ti_msp_dl_config.h not found in {proj} -- run SysConfig first")
        return False
    text = header.read_text(encoding="utf-8", errors="replace")
    macros = _MACRO_RE.findall(text)
    if not macros:
        print("[macros] no peripheral macros found in ti_msp_dl_config.h")
        return True
    width = max(len(name) for name, _ in macros)
    print(f"\n=== Generated macros ({header.name}) -- use these EXACT names in your .c ===")
    for name, value in macros:
        print(f"  {name:<{width}}  {value}")
    print("=== end macros ===\n")
    return True


def _chip_info(config: dict) -> dict:
    """Derive chip-specific build parameters from config['chip'].

    e.g. MSPM0G3507 -> startup family mspm0g350x, macro __MSPM0G3507__,
         linker mspm0g3507.cmd, LP board LP_MSPM0G3507.
    """
    chip = config.get("chip", "MSPM0G3519")
    num = chip[len("MSPM0G"):] if chip.upper().startswith("MSPM0G") else chip[-4:]
    family = "mspm0g" + num[:3] + "x"  # 3507 -> 350x, 3519 -> 351x
    return {
        "chip": chip,
        "macro": f"__{chip}__",
        "startup": f"startup_{family}_ticlang.c",
        "linker_cmd": f"{chip.lower()}.cmd",
        "lp_board": f"LP_{chip}",
    }


def _generate_makefile(ticlang_dir: Path, proj: Path, config: dict) -> None:
    """Generate a minimal makefile for CLI builds (CCS IDE does this automatically)."""
    sdk_root = Path(config.get("sdk_root", ""))
    compiler_bin = Path(config.get("compiler", "")) / "bin"
    info = _chip_info(config)

    # Collect ALL .c files recursively (excluding Debug, ticlang, targetConfigs)
    skip_dirs = {"Debug", "ticlang", "targetConfigs", ".settings"}
    c_files_rel = []
    include_dirs = set()
    for cf in sorted(proj.rglob("*.c")):
        if any(s in cf.parts for s in skip_dirs):
            continue
        rel = cf.relative_to(proj)
        c_files_rel.append(rel)
        if rel.parent != Path("."):
            include_dirs.add(str(rel.parent))

    if not c_files_rel:
        return  # no sources yet, skip makefile generation

    # Also add subdirs that have .h files only (for include paths)
    for d in sorted(proj.rglob("*")):
        if d.is_dir() and not any(s in d.parts for s in skip_dirs):
            if list(d.glob("*.h")):
                rel = d.relative_to(proj)
                include_dirs.add(str(rel))

    inc_flags = " ".join(f"-I../{d}" for d in sorted(include_dirs)).replace("\\", "/")

    c_files = [str(f).replace("\\", "/") for f in c_files_rel]

    # Startup file → copy to project ROOT (makefile references ../startup_xxx.c)
    startup_src = sdk_root / "source/ti/devices/msp/m0p/startup_system_files/ticlang" / info["startup"]
    startup_dst = proj / info["startup"]
    if startup_src.exists() and not startup_dst.exists():
        shutil.copy2(startup_src, startup_dst)
    if startup_dst.exists():
        c_files.append(info["startup"])

    # Copy device_linker.cmd (try example dir first, then SDK linker_files)
    linker_src = sdk_root / "examples/nortos" / info["lp_board"] / "driverlib/gpio_toggle_output/ticlang/device_linker.cmd"
    if not linker_src.exists():
        linker_src = sdk_root / "source/ti/devices/msp/m0p/linker_files/ticlang" / info["linker_cmd"]
    linker_dst = ticlang_dir / "device_linker.cmd"
    if linker_src.exists():
        shutil.copy2(linker_src, linker_dst)

    # Generate makefile
    makefile = f"""# Auto-generated by build.py
MSPM0_SDK_INSTALL_DIR = {sdk_root}
TICLANG_ARMCOMPILER    = {compiler_bin}
CC   = "${{TICLANG_ARMCOMPILER}}/tiarmclang"
LNK  = "${{TICLANG_ARMCOMPILER}}/tiarmclang"

CFLAGS = -I.. -I. {inc_flags} \\
    -I"${{MSPM0_SDK_INSTALL_DIR}}/source/third_party/CMSIS/Core/Include" \\
    -I"${{MSPM0_SDK_INSTALL_DIR}}/source" \\
    -D{info["macro"]} -gdwarf-3 -mcpu=cortex-m0plus -march=thumbv6m \\
    -mfloat-abi=soft -mlittle-endian -mthumb -O1

LFLAGS = -Wl,--rom_model -Wl,--warn_sections \\
    -L"${{MSPM0_SDK_INSTALL_DIR}}/source" \\
    -L.. -L. \\
    -Wl,-l"{linker_dst.name}" \\
    -ldevice.cmd.genlibs \\
    -L"${{TICLANG_ARMCOMPILER}}/lib" \\
    -llibc.a

OBJECTS = {' '.join(Path(cf).stem + '.o' for cf in c_files)}
NAME    = {proj.name}

all: $(NAME).out

$(NAME).out: $(OBJECTS)
\t$(LNK) $(OBJECTS) $(LFLAGS) -o $(NAME).out

"""
    for cf in c_files:
        stem = Path(cf).stem
        src_path = f"../{cf}".replace("\\", "/")
        makefile += f"{stem}.o: {src_path}\n"
        makefile += f"\t$(CC) $(CFLAGS) -c {src_path} -o $@\n\n"

    makefile += "clean:\n\trm -f $(OBJECTS) $(NAME).out $(NAME).map\n"
    (ticlang_dir / "makefile").write_text(makefile, encoding="utf-8")


def main(
    project_dir: str,
    config_path: str | None = None,
    _interactive: bool = True,
    sysconfig_only: bool = False,
) -> tuple[bool, str]:
    cfg_path = config_path or str(Path(__file__).resolve().parents[1] / "config.json")
    if not Path(cfg_path).exists():
        return False, (
            "config.json 不存在。请先运行 `python scripts/setup.py` 配置工具链路径，"
            "或手动创建 config.json（参考 SKILL.md 的 Path Configuration 章节）。"
        )
    config = _load_config(cfg_path)
    info = _chip_info(config)

    proj = Path(project_dir).resolve()
    syscfg_files = list(proj.glob("*.syscfg"))
    if not syscfg_files:
        return False, f"No .syscfg file found in {proj}"
    syscfg = syscfg_files[0]

    sysconfig_cli = config.get("sysconfig_cli", "sysconfig_cli.bat")
    gmake = config.get("gmake", "gmake")
    sdk_root = config.get("sdk_root", "")
    if not Path(sysconfig_cli).exists():
        return False, (
            f"SysConfig CLI 未找到：{sysconfig_cli}\n"
            "请检查 config.json 中的 sysconfig_cli 路径，或运行 setup.py 重新配置。"
        )
    product_json = str(Path(sdk_root) / ".metadata" / "product.json")

    # Step 1: SysConfig
    if _interactive:
        response = input(
            f"\nRun SysConfig CLI? (y/n)\n"
            f"  Path: {sysconfig_cli}\n"
            f"  Target: {syscfg}\n"
        )
        if response.lower() not in ("y", "yes", ""):
            return False, "User declined SysConfig step"

    sysconfig_cmd = [
        sysconfig_cli, "--compiler", "ticlang",
        "--product", product_json, "--output", str(proj), str(syscfg),
    ]
    print(f"[SysConfig] {' '.join(sysconfig_cmd)}")
    result = subprocess.run(sysconfig_cmd, capture_output=True, text=True,
                            encoding="utf-8", errors="replace", cwd=str(proj))
    if result.returncode != 0:
        return False, f"SysConfig failed:\n{result.stderr}\n{result.stdout}"

    # --sysconfig-only: stop here. Print the ground-truth macro names so the agent
    # can write the .c with correct macros and avoid the first-build failure.
    if sysconfig_only:
        print_generated_macros(proj)
        header = proj / "ti_msp_dl_config.h"
        return True, str(header)

    # NOTE: Do NOT delete ti_msp_dl_config.c/h here.
    # CLI build (ticlang/makefile) uses -I.. and compiles ../ti_msp_dl_config.c directly.
    # These files must stay in project root for the makefile to find them.
    # cleanup.py removes stale copies BEFORE SysConfig runs; build.py must not remove fresh ones.

    # After SysConfig: copy startup file from ticlang/ to project root
    # (SysConfig CLI outputs to --output dir, but makefile expects it at project root)
    startup_name = info["startup"]
    startup_in_ticlang = proj / "ticlang" / startup_name
    startup_in_root = proj / startup_name
    if startup_in_ticlang.exists() and not startup_in_root.exists():
        shutil.copy2(startup_in_ticlang, startup_in_root)

    # Patch startup file: add missing UART7_IRQHandler (G3519 wireless module only)
    if info["chip"].upper() == "MSPM0G3519":
        startup_file = startup_in_root if startup_in_root.exists() else (startup_in_ticlang if startup_in_ticlang.exists() else None)
        if startup_file and startup_file.exists():
            content = startup_file.read_text(encoding="utf-8")
            if "UART7_IRQHandler" not in content:
                content = content.replace(
                    "void Default_Handler(void)",
                    "void UART7_IRQHandler(void) __attribute__((weak, alias(\"Default_Handler\")));\nvoid Default_Handler(void)")
                vector_pattern = r"(TIMA1_IRQHandler,\s*\n\s*)0,\s*// Index 28"
                content = re.sub(vector_pattern, r"\1UART7_IRQHandler,  // Index 28 (UART7)", content)
                if "UART7_IRQHandler" in content:
                    startup_file.write_text(content, encoding="utf-8")
                    print("[patch] added UART7_IRQHandler to startup file")

    # Step 2: Ensure ticlang/ and makefile exist (SysConfig may create ticlang/ but no makefile)
    ticlang_dir = proj / "ticlang"
    ticlang_dir.mkdir(exist_ok=True)
    if not (ticlang_dir / "makefile").exists():
        _generate_makefile(ticlang_dir, proj, config)

    if _interactive:
        response = input(f"\nRun gmake? (y/n)\n  Dir: {ticlang_dir}\n")
        if response.lower() not in ("y", "yes", ""):
            return False, "User declined gmake step"

    gmake_cmd = [gmake, "-C", str(ticlang_dir)]
    print(f"[gmake] {' '.join(gmake_cmd)}")
    result = subprocess.run(gmake_cmd, capture_output=True, text=True,
                            encoding="utf-8", errors="replace", cwd=str(ticlang_dir))

    if result.returncode != 0:
        return False, f"gmake failed:\n{result.stderr}\n{result.stdout}"

    out_files = list(ticlang_dir.glob("*.out"))
    out_path = str(out_files[0]) if out_files else f"{ticlang_dir}/{proj.name}.out"
    return True, out_path


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Build CCS project")
    parser.add_argument("project_dir", help="Path to project directory")
    parser.add_argument("-y", "--yes", action="store_true", help="Skip interactive prompts")
    parser.add_argument("--rebuild", action="store_true", help="Delete ticlang/ and regenerate makefile from scratch")
    parser.add_argument("--sysconfig-only", action="store_true",
                        help="Run only SysConfig, then print generated macro names and stop (no gmake). "
                             "Use this after editing .syscfg to get ground-truth macros BEFORE writing the .c.")
    args = parser.parse_args()
    if args.rebuild:
        ticlang = Path(args.project_dir) / "ticlang"
        if ticlang.exists():
            shutil.rmtree(ticlang)
            print("[rebuild] removed ticlang/ for fresh regeneration")
    # --sysconfig-only is meant for non-interactive agent use; skip prompts.
    interactive = not (args.yes or args.sysconfig_only)
    ok, msg = main(args.project_dir, _interactive=interactive, sysconfig_only=args.sysconfig_only)
    if ok:
        if args.sysconfig_only:
            print(f"\nSysConfig done\n  Header: {msg}")
        else:
            print(f"\nBuild successful\n  Output: {msg}")
    else:
        print(f"\nBuild failed\n{msg}")
        raise SystemExit(1)
